# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'

target 'GroceryApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for GroceryApp
  pod 'Firebase/Core'

  target 'GroceryApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'GroceryAppTests' do
    inherit! :search_paths
    # Pods for testing

  end

end
